import type { Metadata } from 'next'

import '../styles/globals.css'
import { Footer, Navbar } from '@/components'

export const metadata: Metadata = {
  title: 'AJIMS Journal',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="relative">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
